
language: python
python:
  - "3.6"

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_0869a03f53b1_key 
    -iv $encrypted_0869a03f53b1_iv
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

install:
  - pip install -r requirements.txt

script: 
  - mkdocs build
  - mkdocs gh-deploy