language: python
python:
- '3.6'
env:
  global:
  - GIT_NAME: "'Markdown autodeploy'"
  - GH_REF: git@github.com:srtsignin/docs.git
install:
- pip install -r requirements.txt
script:
- openssl aes-256-cbc -K $encrypted_0869a03f53b1_key -iv $encrypted_0869a03f53b1_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- git config user.name "Automatic Publish"
- git remote add gh-token "${GH_REF}";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- "Pushing to github"; PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages;
