site_name: SRT Sign In
repo_url: https://github.com/srtsignin/

theme:
    name: 'material'
    palette:
        primary: 'deep purple'
        accent: 'purple'
    feature:
        tabs: true
    logo:
        icon: 'cloud'

plugins:
   - search
   - awesome-pages:
        collapse_single_pages: true

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.tasklist:
        custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png



