site_name: SRT Sign In
repo_url: https://github.com/srtsignin/

theme:
    name: 'material'
    palette:
        primary: 'deep purple'
        accent: 'purple'

plugins:
   - search
   - awesome-pages:
        collapse_single_pages: true

markdown_extensions:
  - admonition
  - footnotes


