site_name: SRT Sign In
repo_url: https://github.com/srtsignin/

theme:
    name: 'material'

plugins:
   - search
   - awesome-pages:
        disable_auto_arrange_index: true
        collapse_single_pages: true

markdown_extensions:
  - admonition
  - footnotes


